#!/bin/bash
docker buildx build --pull --push --platform=linux/amd64 -f $DOCKERFILE_PATH -t ${IMAGE_NAME}_amd64 .
docker buildx build --pull --push --platform=linux/arm64 -f $DOCKERFILE_PATH -t ${IMAGE_NAME}_arm64 .