#!/bin/bash
docker buildx create --use
docker buildx build --pull --push --no-cache --platform=linux/amd64 -f $DOCKERFILE_PATH -t ${IMAGE_NAME}-amd64 .
docker buildx build --pull --push --no-cache --platform=linux/arm64 -f $DOCKERFILE_PATH -t ${IMAGE_NAME}-arm64 .
docker manifest create ${IMAGE_NAME} --amend ${IMAGE_NAME}-amd64 --amend ${IMAGE_NAME}-arm64
docker manifest push ${IMAGE_NAME}