#!/bin/bash
docker buildx create --use
docker buildx build --pull --push --no-cache --platform=linux/amd64 -f $DOCKERFILE_PATH -t ${IMAGE_NAME}_amd64 .
docker buildx build --pull --push --no-cache --platform=linux/arm64 -f $DOCKERFILE_PATH -t ${IMAGE_NAME}_arm64 .